// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBTi9UursOW0kbzgIWy87WPgYCDxx39F0',
    appId: '1:1016811560093:web:2daef68b4dd40bf5e7c874',
    messagingSenderId: '1016811560093',
    projectId: 'commute-b6e12',
    authDomain: 'commute-b6e12.firebaseapp.com',
    storageBucket: 'commute-b6e12.firebasestorage.app',
    measurementId: 'G-JGF51EC2BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnUhVnM8gol00sVFNaqgOvqlyr4srxRhI',
    appId: '1:1016811560093:android:47b6d8f0ae5c881be7c874',
    messagingSenderId: '1016811560093',
    projectId: 'commute-b6e12',
    storageBucket: 'commute-b6e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8e48iZqKYqg2Z8LmfvFjDTYAJ_BhmnVw',
    appId: '1:1016811560093:ios:8419d563b4927cdee7c874',
    messagingSenderId: '1016811560093',
    projectId: 'commute-b6e12',
    storageBucket: 'commute-b6e12.firebasestorage.app',
    iosClientId: '1016811560093-6tu0glbmsfgug81mfj71idlv9p53jhkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.openhackCommute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8e48iZqKYqg2Z8LmfvFjDTYAJ_BhmnVw',
    appId: '1:1016811560093:ios:8419d563b4927cdee7c874',
    messagingSenderId: '1016811560093',
    projectId: 'commute-b6e12',
    storageBucket: 'commute-b6e12.firebasestorage.app',
    iosClientId: '1016811560093-6tu0glbmsfgug81mfj71idlv9p53jhkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.openhackCommute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBTi9UursOW0kbzgIWy87WPgYCDxx39F0',
    appId: '1:1016811560093:web:c04e508771f5283fe7c874',
    messagingSenderId: '1016811560093',
    projectId: 'commute-b6e12',
    authDomain: 'commute-b6e12.firebaseapp.com',
    storageBucket: 'commute-b6e12.firebasestorage.app',
    measurementId: 'G-W7CHSJCGJM',
  );
}